### ISSUE TITLE
images

### ISSUE THREAD

**Issue by Compound-codes** [python-nerd-3/brokemon#1]
you should make horribly drawn icons to represent the other eperson

**Comment by python-nerd-3** [comment]
can you go into detail more i dont understandamundo

**Comment by Compound-codes** [comment]
make the levels brokemon, and give them an icon: 
![image](https://user-images.githubusercontent.com/68404606/216979577-dfecf5be-a0d1-4079-b5ec-6effd50583b1.png)

**Comment by python-nerd-3** [comment]
pekachu
